### ISSUE TITLE
打不开 https://htdij.apachecn.org/ 浏览

### ISSUE THREAD

**Issue by cv3x** [apachecn/howtodoinjava-zh#3]
https://htdij.apachecn.org/

这个网址在我家里的网络打不开（360测速显示是联通），公司的电信宽带网络可以打开，这是什么情况？

![edge](https://user-images.githubusercontent.com/27403411/89320541-2fa4ac80-d6b4-11ea-975d-0ab550093c58.png)

ping 域名显示是 127.0.0.1 的，如下：

![ping](https://user-images.githubusercontent.com/27403411/89320395-02f09500-d6b4-11ea-89e6-908481e5a1a0.png)

**Comment by jiangzhonglian** [comment]
需要翻墙 

![image](https://user-images.githubusercontent.com/9199175/89365242-c8641800-d706-11ea-87cc-318c341f60d6.png)

**Comment by cv3x** [comment]
> 需要翻墙
> 
> ![image](https://user-images.githubusercontent.com/9199175/89365242-c8641800-d706-11ea-87cc-318c341f60d6.png)

可以放到国内吗？因为不是每个人都经常FQ。
PS：为什么公司网络不FQ都可以正常打开？

**Comment by wizardforcel** [comment]
联通的出海线路最近有点问题，请打 10010 反馈

http://www.17ce.com/site/http/20200811_95d318a0db8e11ea8d1cdb50ba3ecec9:1.html
